#!/usr/bin/env perl
# /**---------------------------------------------------------------------------
#
#         File: cma2loc
#
#        Usage: cma2loc $file
#
#  Description: 
#
#      Options: ---
# Requirements: ---
#         Bugs: ---
#        Notes: ---
#       Author: Liang Peng (...), pengliang@piesat
# Organization: ...
#      Version: 1.0
#      Created: 2021年02月23日 10时33分07秒
#     Revision: ---
# ----------------------------------------------------------------------------*/

use strict;
use warnings;
use utf8;

# parameter input
my @file = @ARGV;
my $out = `pwd`;
chomp($out);
my $natapp = "/home/leon/data/natapp-tmp";
my $rp = "origin";
my $b = '';
my $rmgit = 'yes';
system("mkdir $out") if !-e $out;

# time
my ($sec,$min,$hour,$mday,$mon,$year) = localtime();
$year = $year+1900;
$mon ++;
my $time = "$year-$mon-${mday}_$hour.$min.$sec";

my $file = ' ';
for my $f (@file) {
    if ($f =~ /^-/) {
        if ($f =~ /^-outpath=/) {
            ($out) = $f =~ /-outpath=(.*)$/;
        }
        if ($f =~ /^-o=/) {
            ($out) = $f =~ /-o=(.*)$/;
        }
        if ($f =~ /^-rp=/) {
            ($rp) = $f =~ /-rp=(.*)$/;
        }
        if ($f =~ /^-branch=/) {
            ($b) = $f =~ /-branch=(.*)$/;
        }
        if ($f =~ /^-natapp=/) {
            ($natapp) = $f =~ /-natapp=(.*)$/;
        }
        if ($f =~ /^-rmgit=/) {
            ($rmgit) = $f =~ /-rmgit=(.*)$/;
        }
    } else {
        $file = "$file 10.24.237.31:$f";
    }
}
$b = "$time$b";

chdir $natapp;
system("git pull $rp master");
my $t = `tail -n1 output`;
my ($p) = $t =~ /:(\d\d\d\d\d) /;
system("
ssh -p $p ads\@server.natappfree.cc << EHP
mkdir /home/ads/data$b/
scp -r $file /home/ads/data$b/
cd /home/ads
tar -cvf /home/ads/data$b.tar data$b
EHP
");

system("scp -r -P $p ads\@server.natappfree.cc:/home/ads/data$b.tar $out/");
