#!/usr/bin/perl

my $file = shift;
my $str = shift;

my @files = glob($file);
foreach my $f (@files) {
  open(DATA, "<$f") or die "can not open $file, $!";
  my $i = 0;
  while(<DATA>){
     $i++;
     if ($_ =~ /$str/i) {
       print "$f\n";
       print "$i: $_\n";
     }
  }
}

