#!/usr/bin/bash

set -e
export LANG=zh_CN.utf8
export XIM="ibus"
export XMODIFIERS="@im=ibus"
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus"

wine /home/leon/.wine/drive_c/Program\ Files\ \(x86\)/Microsoft\ Office/Office12/VISIO.EXE

